# ***********************************************************************
# @copyright    : Siemens AG
# @license      : GPLv3
# @author       : Andreas Kaeberlein
# @address      : Clemens-Winkler-Strasse 3, 09116 Chemnitz
#
# @maintainer   : Andreas Kaeberlein
# @telephone    : +49 371 4810-2108
# @email        : andreas.kaeberlein@siemens.com
#
# @file         : linux.yml
# @date         : 2023-08-04
# @see          : https://github.com/andkae/usbiss
#
# @brief        : Linux CI Compile
#
# **********************************************************************/


name: Linux

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: OS Version
        run: cat /etc/os-release
      - name: Build
        run: make
