# ***********************************************************************
# @copyright    : Siemens AG
# @license      : GPLv3
# @author       : Andreas Kaeberlein
# @address      : Clemens-Winkler-Strasse 3, 09116 Chemnitz
#
# @maintainer   : Andreas Kaeberlein
# @telephone    : +49 371 4810-2108
# @email        : andreas.kaeberlein@siemens.com
#
# @file         : windows.yml
# @date         : 2023-08-04
# @see          : https://github.com/andkae/usbiss
# @see          : https://github.com/msys2/setup-msys2
#
# @brief        : Windows compile exe
#
# **********************************************************************/


name: Windows

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Windows EOL
        run: git config --global core.autocrlf input
      - name: Repo check out
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-libsystre make git
      - name: Compile
        shell: msys2 {0}
        run: |
          pwd
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: usbiss-win-${{github.ref_name}}
          path: .\bin\usbiss.exe
          retention-days: 30
